### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by mfolnovic** [kpisacic/DHMZ-home-assistant-custom-component#10]
It seems they removed the https://vrijeme.hr/kompozit-anim.gif, and it's now separate images:

https://vrijeme.hr/radari/anim_kompozit1.png
https://vrijeme.hr/radari/anim_kompozit2.png
...
https://vrijeme.hr/radari/anim_kompozit25.png

**Comment by kpisacic** [comment]
I was thinking for some time how to do this without downloading every 5 minutes (what is now refresh interval for radar images) all 25 images - and i have an idea, so just information i will start working on that.
For the time, i have just replaces animated URL with static one, to show instead of camera in this commit: https://github.com/kpisacic/DHMZ-home-assistant-custom-component/commit/804311c51f0ea417ddf938f1d6875031d9987d32 .

**Comment by kpisacic** [comment]
Hi, last commit https://github.com/kpisacic/DHMZ-home-assistant-custom-component/commit/fad454caf42527b07c1fe0a6e22baee6689d2df8 has full working version. Check changes in configuration and report any issues/bugs.
